### ISSUE TITLE
Suggestion: Easy way to Switch to Indentation-Style Code Blocks 

### ISSUE THREAD

**Issue by ricealexander** [Sabrehvardas/backtickbot#5]
I hope this issue finds you well.

I opted out of backtickbot because I felt that indentation-style code blocks were too much of a hassle, particularly when formatting large code blocks with empty lines. I'd left a comment that if there were an easy alternative to manually indenting code blocks, that I would be interested.

There is an easy way.

Anyone using the Markdown Editor can "Switch to Fancy Pants Editor" and their code blocks are automatically converted to indentation-style code blocks

Before I post, right before I press the COMMENT button, I'll "Switch to Fancy Pants Editor" and switch back, and my indentation style will be changed.

It might be worth adding language to your bot's responses that Markdown Editor users can switch their editor and switch back immediately to convert their indentation style automatically.

**Comment by Sabrehvardas** [comment]
I added  some mention of it. Might increase the length a bit though.
